=== Zadest/x-tech/recipe.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT recipe (keywords,ingredients,instructions)>
<!ATTLIST recipe key CDATA "">
<!ELEMENT keywords (keyword*)>
<!ELEMENT keyword (#PCDATA)>
<!ELEMENT ingredients (ingredient+)>
<!ELEMENT ingredient (num*,unit*,identifier*)>
<!ELEMENT identifier (#PCDATA) >
<!ELEMENT num (#PCDATA) >
<!ELEMENT unit (#PCDATA)>
<!ELEMENT instructions (#PCDATA)>

=== Zadest/x-tech/recipe_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipe SYSTEM "recipe.dtd">
<recipe key="wirsing-pfanne">
   <keywords>
       <keyword></keyword>
   </keywords>
   <ingredients>
       <ingredient>
           <num></num>
           <unit></unit>
           <identifier></identifier>
       </ingredient>
   </ingredients>
   <instructions>
       
   </instructions>
</recipe>
